### ISSUE TITLE
Assignment Progress

### ISSUE THREAD

**Issue by dluman** [term-world/woodshop-assignment#1]
# `TODO`s

Based on the GatorGrader report for this run, here's a summary of what you've got left to do.

## Reflection

- [ ] No TODO markers left in reflection.md

## WoodPile Woes

- [ ] No TODO markers left in WoodPile.py
- [x] WoodPile.py constructor takes no explicit arguments
- [ ] WoodPile.py constructor creates an empty list property called pieces
- [ ] WoodPile.py add method takes one explicit parameter
- [ ] WoodPile.py add method adds the list of Lumber objects to ongoing pieces list

## Lumber Labor

- [ ] No TODO markers left in Lumber.py
- [ ] Lumber.py constructor takes 2 parameters
- [ ] Lumber.py constructor sets the length property

## MatchFileFragment

- [ ] All checkboxes checked

## Didja See the Saw?

- [ ] Saw.py contains at least one comment for each method

## Main Mission

- [ ] main.py imports Saw correctly
- [ ] main.py imports WoodPile correctly
- [ ] main.py imports Lumber correctly
- [ ] main.py creates a Saw object
- [ ] main.py creates a WoodPile object
- [ ] main.py creates Lumber objects
- [ ] main.py adds to the WoodPile
- [ ] main.py uses the Saw
- [ ] main.py calls Plans with list of WoodPile pieces as argument

## Did it Build?

- [x] Chair.py exists in the products&#x2F;
- [x] Table.py exists in the products&#x2F;
- [x] Bookshelf.py exists in the products&#x2F;

## Percent complete

Based on the checks achieved, this assignment is `17%` complete.
